### ISSUE TITLE
Different button classes

### ISSUE THREAD

**Issue by krishnabrchand** [razaanstha/cookiebot-embeds#2]
It would be great if we have different classes for each button so that we can easily style them.
![button-class](https://github.com/razaanstha/cookiebot-embeds/assets/57343614/054b17cc-e0c0-4f6d-8eaa-f2134bce2582)

**Comment by razaanstha** [comment]
Closing this issue as it has been resolved in [version 1.1.5](https://github.com/razaanstha/cookiebot-embeds/releases/tag/1.1.5).
